# Generated by Django 5.0.1 on 2024-01-18 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_surveychoices_surveychoice_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='surveyentry',
            name='question1',
        ),
        migrations.RemoveField(
            model_name='surveyentry',
            name='question2',
        ),
        migrations.RemoveField(
            model_name='surveyentry',
            name='question3',
        ),
        migrations.AddField(
            model_name='surveyentry',
            name='answers',
            field=models.JSONField(default={'Q1': '0'}),
            preserve_default=False,
        ),
    ]
