# Generated by Django 5.0.1 on 2024-01-18 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_surveyentry_question1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyquestion',
            name='val',
            field=models.CharField(default=0, max_length=999),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='surveychoice',
            name='val',
            field=models.CharField(max_length=999),
        ),
    ]
